title: Gabriel Lima
url: "http://thegcamilo.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "[Email](mailto:gabriel.lima@mpi-sp.org) &#124; [LinkedIn](https://www.linkedin.com/in/gabriel-lima-531b271a0/)"

sass:
    style: compressed
    sass_dir: _sass

nav:
#  - name: "About"
#    link: "/researcher/"
 - name: "Publications"
   link: "publications"
 - name: "Service"
   link: "service"
 - name: "Teaching"
   link: "teaching"
 - name: "CV"
   link: "assets/CV.pdf"

